### ISSUE TITLE
add disclaimer about NKN's license to web form frontend

### ISSUE THREAD

**Issue by mguarinello** [northwest-knowledge-network/mdedit#11]
The following text should appear somewhere on the mdedit webform. We should probably check with Luke to see if it needs to be one of those pop-ups that force you to accept terms of use before you can actually use the application.

Per the Northwest Knowledge Network’s terms of service, the default license for use of this content is the Creative Commons License titled Attribution-NonCommercial-ShareAlike, unless otherwise specified by the content contributor. For more information, see http://creativecommons.org. Because NKN will be the distributor of the metadata records created with this application, this license will apply to all records created here.

**Comment by sheneman** [comment]
This wording looks good to me, and I like the explicit mention of how the metadata is licensed with the Creative Commons Attribution-NonCommercial-ShareAlike license.

What we were instructed to do by the UI legal folks was: when somebody logged into the NKN portal for the first time (with their credentials after registering), they should be presented with a popup of the TOS that they would need to read and acknowledge before proceeding.   We were asked to track these acknowledgements for all users for a paper trail.   We track these acknowledgements in the NKN LDAP server.   

In fact, I extended our NKN LDAP schema to include fields SPECIFICALLY for tracking whether somebody acknowledged the TOS.   I did this using the "nknobject" objectClass and a series of attributes.   If you are going to present a clickable TOS, you should use LDAP to track the acknowledgement so that we track this all in one place.   If for some crazy reason you are creating a metadata editor web tool that is separate from the main one on the NKN portal, we may need to track acknowledgement in a different attribute in LDAP.

Here are my LDAP schema extensions:

#
# SHENEMAN
# 03/21/2013
#
attributetype ( 1.3.6.1.4.1.4203.666.1.90
        NAME 'nknTOSDetail'
        DESC 'Detail about the acceptance of NKN terms of service (TOS)'
        EQUALITY caseIgnoreMatch
        SYNTAX 1.3.6.1.4.1.1466.115.121.1.15 SINGLE-VALUE )

attributetype ( 1.3.6.1.4.1.4203.666.1.91
        NAME 'nknTOSTimestamp'
        DESC 'The Timestamp for accepting the NKN Terms of Service'
        EQUALITY caseIgnoreMatch
        SYNTAX 1.3.6.1.4.1.1466.115.121.1.15 SINGLE-VALUE )

attributetype ( 1.3.6.1.4.1.4203.666.1.92
        NAME 'nknAccountActivationDetail'
        DESC 'Detail about NKN Account Activation'
        EQUALITY caseIgnoreMatch
        SYNTAX 1.3.6.1.4.1.1466.115.121.1.15 SINGLE-VALUE )

attributetype ( 1.3.6.1.4.1.4203.666.1.93
        NAME 'nknAccountActivationDate'
        DESC 'The Date of NKN Account Activation'
        EQUALITY caseIgnoreMatch
        SYNTAX 1.3.6.1.4.1.1466.115.121.1.15 SINGLE-VALUE )

attributetype ( 1.3.6.1.4.1.4203.666.1.94
        NAME 'nknConfirmationCode'
        DESC 'The Confirmation Code used by account activation in the NKN portal'
        EQUALITY caseIgnoreMatch
        SYNTAX 1.3.6.1.4.1.1466.115.121.1.15 SINGLE-VALUE )

attributetype ( 1.3.6.1.4.1.4203.666.1.95
        NAME 'nknSambaHost'
        DESC 'The attribute used by NKN to manage Samba share access'
        EQUALITY caseIgnoreMatch
        SYNTAX 1.3.6.1.4.1.1466.115.121.1.15 )

attributetype ( 1.3.6.1.4.1.4203.666.1.96
        NAME 'nknSambaShare'
        DESC 'The attribute used by NKN to list Samba shares on a machine'
        EQUALITY caseIgnoreMatch
        SYNTAX 1.3.6.1.4.1.1466.115.121.1.15 )


objectClass ( 1.3.6.1.4.1.4203.666.1.100
        NAME 'nknobject'
        DESC 'NKN Object'
        AUXILIARY
        MAY ( nknTOSDetail $ nknTOSTimestamp $ nknAccountActivationDetail $ nknAccountActivationDate $ nknConfirmationCode $ nknSambaHost $ nknSambaShare) )

**Comment by flathers** [comment]
BTW, here's a link to the Terms of Service:

https://www.northwestknowledge.net/terms_of_service
