### ISSUE TITLE
Published datasets not showing last pub date and no option to delete

### ISSUE THREAD

**Issue by mtpain** [northwest-knowledge-network/mdedit#126]
Seems to be an intermittent problem. I just published one and my interface didn't show last pub date and still allowed me to delete. B Godfrey published a few records, but his are showing as published with no delete option...

**Comment by mtpain** [comment]
@ccasey645 @flathers Is this done?

**Comment by ccasey645** [comment]
I haven't worked on this issue but I can get on it.

**Comment by ccasey645** [comment]
I might have found part of the problem, but I need to test it.

**Comment by ccasey645** [comment]
Found it: in services.js the statement 

            if (record.hasOwnProperty('md_pub_date') && record.md_pub_date.$date != ''
                && typeof record.md_pub_date.$date !== "undefined")
            {
                serverReady.md_pub_date.$date =
                    record.md_pub_date.$date.getTime();
            }

            else
            {
                delete serverReady.md_pub_date;
            }

is not letting the md_pub_date to be stored to the database. services.js initializes md_pub_date to an empty string (''), so this statement is always deleting md_pub_date from the record. If && record.md_pub_date.$date != '' is removed from the if statement, then the inside of that statement can be evaluated.

However, currentRecord.md_pub_date.$date is not a data object, so the function "                    record.md_pub_date.$date.getTime();" fails, but if you replace that statement with "new Date().getTime();", then it works! 

I just tested this by disabling the http.post to the publish server, shutting off the internet on my local machine, and trying to post, and the publish date appears after the publish attempt. Also, I checked the database record before and after I implemented this fix and before the currentRecord.md_pub_date attribute was not making it to the database, and after the fix currentRecord.md_pub_date is making it to the database. 

I will implement this fix in the formWizard branch. I still need to test the delete button functionality.

**Comment by ccasey645** [comment]
So this turned out to be a little more complicated than I originally thought. The above code was deleting the md_pub_date attribute from the record about to be saved, but a bug in MongoDB (https://github.com/MongoEngine/mongoengine/issues/734) doesn't allow for dateTimeField objects to be null or a string of length 0. If the value used to construct the dateTimeField class is null or a string of length 0, then that attribute is deleted from the database. So the above code along with this bug was why the md_pub_date was not making it to the database.

I have a work around, but it is something that is usually should be avoided with Javascript projects. I re-add the md_pub_date attribute to the record object right before publishing, and then publish, and md_pub_date is then inserted into the database. MongoDB usually allows for null values (http://docs.mongoengine.org/apireference.html#fields), but with the dateTimeField class having this bug I do not really see a way around this. 

Anyone have any thoughts? If not, I will probably use this approach since it works.

**Comment by ccasey645** [comment]
This has been fixed in the most recent version of the Metadata editor.
