### ISSUE TITLE
Make more clear when record has not been published

### ISSUE THREAD

**Issue by mtpain** [northwest-knowledge-network/mdedit#127]

**Comment by ccasey645** [comment]
I think that the form wizard we developed guides the user to the final step, which is submitting the record for publication. So, I think that this has been addressed. Anyone have any thoughts?

**Comment by flathers** [comment]
I believe the original complaint came because contributors didn't understand that they needed to press the 'submit for publication' button.  I think it's a lot more clear now, but maybe we could put a sentence at the top of the 'review & submit' page that reminds them that they need to press the button at the bottom of the page to actually submit?

**Comment by ccasey645** [comment]
That sounds good. I will add that text to the review and submit page and that will make it into the next iteration.

**Comment by ccasey645** [comment]
Here is what I have so far. I tried to make it as succinct as possible. Any thoughts? Should it be shorter?

![image](https://cloud.githubusercontent.com/assets/10604966/19897882/212177d8-a017-11e6-93c9-3b531321a47a.png)
