### ISSUE TITLE
No way to associate contacts with resources

### ISSUE THREAD

**Issue by flathers** [northwest-knowledge-network/mdedit#145]
A client created a metadata record for a dataset that is distributed by multiple distributors (NKN and the USGS).  He created a Contact for each distributor, and then added a Resource for each download URL.  When the record comes out as ISO, it lists both Resources for both Contacts, which means that when we get search results on the web, we see multiple instances of each link.

It's not totally obvious to me what approach to take in fixing this.  Make a drop-down list in the Resources page that allows a Resource to be associated with a Contact?

**Comment by ccasey645** [comment]
Or, could we make another field in the Contacts section that is for a URL for each contact that would be optional? I don't think that the URL in the Resources is set up to be exclusively associated with a contact, so one of those resources would have to be associated with a contact probably with a drop down selection list like you suggested, or we could make another field in the Contacts section for a URL for that contact.

**Comment by ccasey645** [comment]
Also, the only real way to model relations in a noSQL database such as MongoDB is to have redundant data. So to associate a contact with a resource we would have to add another attribute to the contact list in the record object in the database that has the resource URL again. I guess we could make a new attribute on the citations and access contacts that are set in the "Resources" section with a dropdown list like you said, and if a contact is selected from that list for a URL, then add the URL to the citations or access object instead of the "online" array where URL's are being stored now.

**Comment by flathers** [comment]
I feel like there's something a little unexpected about having the URL field in the Contacts section, and users might not be able to find it there.  So maybe your second idea is better?  I guess, for most cases, there will only be one contact and one resource URL, so most users would never have to interact with that dropdown box.

**Comment by ccasey645** [comment]
Yeah it is probably better to just make the code do it and not make the UI overly complicated. I'll make a new branch and start working on this. I'm still working on getting the branch that makes the Start Date and End Date optional working 100%, so it might be a couple of days until I can start on this.

**Comment by flathers** [comment]
Okay, no worries.  As Bruce has been submitting data, I've just been fixing the metadata by hand, which isn't a big deal at our current volume.

**Comment by ccasey645** [comment]
I have made a new branch called "contactResourceAssign" and deployed it on the development server for the metadata editor. The data model in the database now allows for relating a URL to a Data Access Contact. And the user interface allows the user to do this in the "Resources" sections of the editor.

The next step is changing the metadata editor's XSLT files that generate the XML file when a record is published. Right now, all resource URL's and file download links are being associated with every Data Access contact, but with this new data model in the database we should be able to fix this.

**Comment by ccasey645** [comment]
I have finished the XML formatting for the ISO 19115 XML file, and everything seems to be in the right spot. And I put it on the development server [(here).](https://nkn-dev.nkn.uidaho.edu) Do I need to change the XSLT's for the Dublin Core and ESRI-ISO formats too so that all three have the resource-URL association in their XML outputs? I noticed that the ESRI-ISO and Dublin Core formats do not currently associate any contact with any Resource URL, and just print all Resource URL's in a list.

**Comment by flathers** [comment]
I don't think you have to worry about the other metadata standards... the 19115 is the primary standard that we use that supports this kind of association.  The ESRI-ISO format *might*, but I haven't studied it very closely, since it's almost always created by some ESRI product.  I know they have a particular way that they like to represent distribution info, and it's a little different.

**Comment by ccasey645** [comment]
Ok great. I'm going to run a bunch of tests on this branch, and if they all pass then merge it into the master, and deploy it hopefully next week onto the production server. Then we can worry about fixing existing ISO 19115 records that are already published to fix the Data Search multiple links problem.
