### ISSUE TITLE
script to write output of xslt to an xml file that can be saved in a location

### ISSUE THREAD

**Issue by mguarinello** [northwest-knowledge-network/mdedit#26]
use python probably

**Comment by mtpain** [comment]
is this still valid? We should probably discuss if we'll save the ISO XMLs to the server where the editor API is running or if we will just have a way to send ISO to the NKN portal

**Comment by mguarinello** [comment]
I defer to Ed on this one. The need to write the ISO to a separate file will depend on the set up of the redesigned portal. I think we need to discuss the flow for ISO validation and publication and how the editor and the portal will interact, or at least the initial plan for the interactions.

**Comment by mtpain** [comment]
Ok, I'm remembering what's going on with this issue now.  As I said at the last staff meeting, the metadata editor should only serve ISO XML generated by implementing transformations (`dicttoxml` and the generic XML to ISO XSLT). The editor never saves any sort of XML.

This is maybe open to discussion, but I strongly believe the best design will be to keep the generic XML out of any other part of the NKN Portal because that XML follows no standard other than our ad-hoc standard we're developing as we go. Plus if we use the PHP metadata XSLT service as Ed proposed, we then have to modify two separate codebases every time we want to make changes. This may sound minor but it will turn into a major headache. Better to make the contract between metadata editor and the rest of the Portal be that the metadata editor will send only ISO to be ingested by the Portal.

After we're done developing, I don't think we should expose the generic XML to the public. 

When the user publishes their metadata to our Portal, it should happen as follows:

1. Metadata editor generates ISO XML
2. Metadata editor sends POST HTTP request to an NKN Portal service that accepts new records
3. Portal service does its job publishing metadata

@mguarinello please the [lxml library](http://lxml.de/xpathxslt.html#xslt) to implement the XSLT. After you've got that working, we can talk about how to integrate the transformation into the Flask API.

**Comment by mguarinello** [comment]
Done! Completed this on the iso_transform branch. Will copy over the two files of relevance to master and then create a new branch and issue for modifying these to work interactively with the server.

**Comment by mtpain** [comment]
:+1:
